### PR TITLE
Update 1.1.0 - PolyZone Integration

### LINKED ISSUE #19: [Placeholder] Polyzone and Target Conversion

### PR DESCRIPTION
**Pull request by uShifty**
- PolyZone Integration (Replaced static threads with dynamic self killing threads)
- Implemented QBCore Drawtext
- Modified Items recieved events, No longer a static random number on client join. Random each time recieving the items.
- Added more EN locales (Please update other locales!)

### CODE REVIEW

**Comment by uShifty** [comment]
Related to #19

**Comment by DannysRP** [comment]
When you enter a zone to pick grapes the draw text while stay on the screen if you don't pick the grapes and leave the zone. At that point you can press E at any time and start the grape picking process

**Comment by uShifty** [comment]
> When you enter a zone to pick grapes the draw text will stay on the screen if you don't pick the grapes and leave the zone. At that point you can press E at any time and start the grape picking process

I appreciate that report, I have fixed it in my latest commit.

**Comment by DannysRP** [comment]
Any time! Otherwise the PR works really well

**Comment by i-kulgu** [comment]
Typo : ["end_shift"] = "Your shift at the vienyard has ended!",
It has to be : ["end_shift"] = "Your shift at the vineyard has ended!",

**Comment by DannysRP** [comment]
One issues I have noticed is that after you pick grapes in one spot the option stays there until you leave the zone (even though the spot has moved to a new location) you can keep picking until you leave the zone

**Comment by uShifty** [comment]
> Typo : ["end_shift"] = "Your shift at the vienyard has ended!", It has to be : ["end_shift"] = "Your shift at the vineyard has ended!",

Sounds good will fix it, thank you for brining it up to my attention

**Comment by uShifty** [comment]
> One issues I have noticed is that after you pick grapes in one spot the option stays there until you leave the zone (even though the spot has moved to a new location) you can keep picking until you leave the zone

Should now be fixed, I also removed the drawtext from being shown when you press the button, appreciate you testing

**Pull request merged**
